export const TEMPLES = [
  {
    id: "palani-murugan",
    name: "Palani Murugan Temple",
    short: "Palani",
    weather: "32°C ☀",
    district: "Dindigul",
    state: "Tamil Nadu",
  },
  {
    id: "madurai-meenakshi",
    name: "Madurai Meenakshi Temple",
    short: "Madurai",
    weather: "32°C ☀",
    district: "Madurai",
    state: "Tamil Nadu",
  },
  {
    id: "srirangam",
    name: "Srirangam Temple",
    short: "Srirangam",
    weather: "32°C ☀",
    district: "Tiruchirappalli",
    state: "Tamil Nadu",
  },
  {
    id: "tiruvannamalai",
    name: "Tiruvannamalai Arunachaleswarar Temple",
    short: "Tiruvannamalai",
    weather: "32°C ☀",
    district: "Tiruvannamalai",
    state: "Tamil Nadu",
  },
  {
    id: "rameswaram",
    name: "Rameswaram Temple",
    short: "Rameswaram",
    weather: "32°C ☀",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
  },
  {
    id: "chidambaram",
    name: "Chidambaram Natarajar Temple",
    short: "Chidambaram",
    weather: "32°C ☀",
    district: "Cuddalore",
    state: "Tamil Nadu",
  },
  {
    id: "tiruchendur",
    name: "Tiruchendur Murugan Temple",
    short: "Tiruchendur",
    weather: "32°C ☀",
    district: "Thoothukudi",
    state: "Tamil Nadu",
  },
  {
    id: "samayapuram",
    name: "Samayapuram Mariamman Temple",
    short: "Samayapuram",
    weather: "32°C ☀",
    district: "Tiruchirappalli",
    state: "Tamil Nadu",
  },
  {
    id: "kapaleeshwarar",
    name: "Kapaleeshwarar Temple",
    short: "Mylapore, Chennai",
    weather: "32°C ☀",
    district: "Chennai",
    state: "Tamil Nadu",
  },
  {
    id: "brihadeeswarar",
    name: "Brihadeeswarar Temple",
    short: "Thanjavur",
    weather: "32°C ☀",
    district: "Thanjavur",
    state: "Tamil Nadu",
  },
  {
    id: "virupaksha",
    name: "Virupaksha Temple",
    short: "Hampi",
    weather: "32°C ☀",
    district: "Vijayanagara",
    state: "Karnataka",
  },
  {
    id: "udupi-sri-krishna",
    name: "Udupi Sri Krishna Matha",
    short: "Udupi",
    weather: "32°C ☀",
    district: "Udupi",
    state: "Karnataka",
  },
  {
    id: "murudeshwara",
    name: "Murudeshwara Temple",
    short: "Murudeshwar",
    weather: "32°C ☀",
    district: "Uttara Kannada",
    state: "Karnataka",
  },
  {
    id: "gokarna-mahabaleshwara",
    name: "Mahabaleshwara Temple",
    short: "Gokarna",
    weather: "32°C ☀",
    district: "Uttara Kannada",
    state: "Karnataka",
  },
  {
    id: "chennakeshava",
    name: "Chennakeshava Temple",
    short: "Belur",
    weather: "32°C ☀",
    district: "Hassan",
    state: "Karnataka",
  },
  {
    id: "kukke-subramanya",
    name: "Kukke Subramanya Temple",
    short: "Subramanya",
    weather: "32°C ☀",
    district: "Dakshina Kannada",
    state: "Karnataka",
  },
  {
    id: "dharmasthala",
    name: "Dharmasthala Temple",
    short: "Dharmasthala",
    weather: "32°C ☀",
    district: "Dakshina Kannada",
    state: "Karnataka",
  },
  {
    id: "sringeri",
    name: "Sringeri Sharada Peetham",
    short: "Sringeri",
    weather: "32°C ☀",
    district: "Chikkamagaluru",
    state: "Karnataka",
  },
  {
    id: "mookambika",
    name: "Mookambika Temple",
    short: "Kollur",
    weather: "32°C ☀",
    district: "Udupi",
    state: "Karnataka",
  },
  {
    id: "hoysaleswara",
    name: "Hoysaleswara Temple",
    short: "Halebidu",
    weather: "32°C ☀",
    district: "Hassan",
    state: "Karnataka",
  },
  {
    id: "shirdi-sai",
    name: "Shirdi Sai Baba Temple",
    short: "Shirdi",
    weather: "32°C ☀",
    district: "Ahmednagar",
    state: "Maharashtra",
  },
  {
    id: "siddhivinayak",
    name: "Siddhivinayak Temple",
    short: "Mumbai",
    weather: "32°C ☀",
    district: "Mumbai",
    state: "Maharashtra",
  },
  {
    id: "trimbakeshwar",
    name: "Trimbakeshwar Temple",
    short: "Trimbak",
    weather: "32°C ☀",
    district: "Nashik",
    state: "Maharashtra",
  },
  {
    id: "bhimashankar",
    name: "Bhimashankar Temple",
    short: "Bhimashankar",
    weather: "32°C ☀",
    district: "Pune",
    state: "Maharashtra",
  },
  {
    id: "grishneshwar",
    name: "Grishneshwar Temple",
    short: "Ellora",
    weather: "32°C ☀",
    district: "Aurangabad",
    state: "Maharashtra",
  },
  {
    id: "mahalaxmi-kolhapur",
    name: "Mahalaxmi Temple",
    short: "Kolhapur",
    weather: "32°C ☀",
    district: "Kolhapur",
    state: "Maharashtra",
  },
  {
    id: "shani-shingnapur",
    name: "Shani Shingnapur",
    short: "Shingnapur",
    weather: "32°C ☀",
    district: "Ahmednagar",
    state: "Maharashtra",
  },
  {
    id: "tulja-bhavani",
    name: "Tulja Bhavani Temple",
    short: "Tuljapur",
    weather: "32°C ☀",
    district: "Dharashiv",
    state: "Maharashtra",
  },
  {
    id: "pandharpur-vitthal",
    name: "Vithoba Temple",
    short: "Pandharpur",
    weather: "32°C ☀",
    district: "Solapur",
    state: "Maharashtra",
  },
  {
    id: "jejuri-khandoba",
    name: "Khandoba Temple",
    short: "Jejuri",
    weather: "32°C ☀",
    district: "Pune",
    state: "Maharashtra",
  },
  {
    id: "somnath",
    name: "Somnath Temple",
    short: "Prabhas Patan",
    weather: "32°C ☀",
    district: "Gir Somnath",
    state: "Gujarat",
  },
  {
    id: "dwarkadhish",
    name: "Dwarkadhish Temple",
    short: "Dwarka",
    weather: "32°C ☀",
    district: "Devbhumi Dwarka",
    state: "Gujarat",
  },
  {
    id: "akshardham-gandhinagar",
    name: "BAPS Akshardham",
    short: "Gandhinagar",
    weather: "32°C ☀",
    district: "Gandhinagar",
    state: "Gujarat",
  },
  {
    id: "ambaji",
    name: "Ambaji Temple",
    short: "Ambaji",
    weather: "32°C ☀",
    district: "Banaskantha",
    state: "Gujarat",
  },
  {
    id: "modhera-sun",
    name: "Sun Temple",
    short: "Modhera",
    weather: "32°C ☀",
    district: "Mehsana",
    state: "Gujarat",
  },
  {
    id: "palitana",
    name: "Palitana Jain Temples",
    short: "Palitana",
    weather: "32°C ☀",
    district: "Bhavnagar",
    state: "Gujarat",
  },
  {
    id: "rukmini-devi",
    name: "Rukmini Devi Temple",
    short: "Dwarka",
    weather: "32°C ☀",
    district: "Devbhumi Dwarka",
    state: "Gujarat",
  },
  {
    id: "pavagadh-kalika",
    name: "Kalika Mata Temple",
    short: "Pavagadh",
    weather: "32°C ☀",
    district: "Panchmahal",
    state: "Gujarat",
  },
  {
    id: "swaminarayan-kalupur",
    name: "Shree Swaminarayan Mandir",
    short: "Ahmedabad",
    weather: "32°C ☀",
    district: "Ahmedabad",
    state: "Gujarat",
  },
  {
    id: "dakor-ranchhodrai",
    name: "Ranchhodrai Temple",
    short: "Dakor",
    weather: "32°C ☀",
    district: "Kheda",
    state: "Gujarat",
  },
];

export type Temple = (typeof TEMPLES)[number];

export const NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", icon: "Home" },
  { id: "heatmap", label: "AI Heatmap", icon: "Flame" },
  { id: "cctv", label: "CCTV Monitor", icon: "Video" },
  // { id: "queue", label: "Queue Management", icon: "Timer" },
  { id: "staff", label: "Volunteer Staff", icon: "UsersRound" },
  { id: "operations", label: "Temple Operations", icon: "Landmark" },
  { id: "parking", label: "Parking", icon: "Car" },
  { id: "darshan", label: "Bookings", icon: "Ticket" },
  { id: "donations", label: "Donations & Funds", icon: "IndianRupee" },
  { id: "annadhanam", label: "Annadhanam", icon: "Utensils" },
  // { id: "announcements", label: "Announcements", icon: "Megaphone" },
  // { id: "analytics", label: "Analytics", icon: "BarChart3" },
  // { id: "emergency", label: "Emergency", icon: "Siren" },
] as const;

export type SectionId = (typeof NAV_ITEMS)[number]["id"];

export const STAFF = [
  {
    id: "S-001",
    name: "Murugan K.",
    role: "Queue Marshal",
    zone: "Lane A",
    status: "duty",
    since: "10:00 AM",
  },
  {
    id: "S-002",
    name: "Selvi R.",
    role: "Volunteer",
    zone: "Lane B",
    status: "duty",
    since: "10:00 AM",
  },
  {
    id: "S-003",
    name: "Arun P.",
    role: "Senior Marshal",
    zone: "Gopuram",
    status: "duty",
    since: "06:00 AM",
  },
  {
    id: "S-004",
    name: "Priya S.",
    role: "Volunteer",
    zone: "Break Room",
    status: "break",
    since: "13:45",
  },
  {
    id: "S-005",
    name: "Karthik V.",
    role: "Queue Marshal",
    zone: "Lane C",
    status: "duty",
    since: "08:00 AM",
  },
  {
    id: "S-006",
    name: "Lakshmi N.",
    role: "Volunteer",
    zone: "Prasad Counter",
    status: "duty",
    since: "09:00 AM",
  },
  {
    id: "S-007",
    name: "Raja M.",
    role: "Security",
    zone: "North Gate",
    status: "duty",
    since: "06:00 AM",
  },
  {
    id: "S-008",
    name: "Devi A.",
    role: "Volunteer",
    zone: "Footwear",
    status: "duty",
    since: "07:00 AM",
  },
  {
    id: "S-009",
    name: "Senthil B.",
    role: "Parking Marshal",
    zone: "Lot A",
    status: "duty",
    since: "06:00 AM",
  },
  {
    id: "S-010",
    name: "Kavitha R.",
    role: "Volunteer",
    zone: "Lane A",
    status: "duty",
    since: "10:00 AM",
  },
  {
    id: "S-011",
    name: "Ganesh T.",
    role: "Senior Marshal",
    zone: "Sanctum",
    status: "duty",
    since: "06:00 AM",
  },
  {
    id: "S-012",
    name: "Anitha P.",
    role: "Volunteer",
    zone: "Break Room",
    status: "break",
    since: "14:00",
  },
  {
    id: "S-013",
    name: "Vimal K.",
    role: "Security",
    zone: "South Gate",
    status: "duty",
    since: "08:00 AM",
  },
  {
    id: "S-014",
    name: "Meena S.",
    role: "Volunteer",
    zone: "VIP Lane",
    status: "duty",
    since: "10:00 AM",
  },
  {
    id: "S-015",
    name: "Suresh R.",
    role: "Queue Marshal",
    zone: "Lane B",
    status: "duty",
    since: "10:00 AM",
  },
  {
    id: "S-016",
    name: "Radha M.",
    role: "Volunteer",
    zone: "Prasad Counter",
    status: "off",
    since: "—",
  },
  {
    id: "S-017",
    name: "Mani P.",
    role: "Parking Marshal",
    zone: "Lot B",
    status: "duty",
    since: "08:00 AM",
  },
  {
    id: "S-018",
    name: "Jaya L.",
    role: "Volunteer",
    zone: "Information",
    status: "duty",
    since: "09:00 AM",
  },
  {
    id: "S-019",
    name: "Bala K.",
    role: "Security",
    zone: "East Gate",
    status: "break",
    since: "13:50",
  },
  {
    id: "S-020",
    name: "Uma D.",
    role: "Senior Marshal",
    zone: "Lane A",
    status: "duty",
    since: "06:00 AM",
  },
];

export const CCTV_CAMERAS = [
  { id: "CAM-P01", name: "Main Gopuram Entrance", count: 187, type: "people", status: "BUSY" },
  { id: "CAM-P02", name: "Queue Lane A", count: 220, type: "people", status: "CROWDED" },
  { id: "CAM-P03", name: "Queue Lane B", count: 178, type: "people", status: "BUSY" },
  { id: "CAM-P04", name: "Inner Sanctum Approach", count: 145, type: "people", status: "NORMAL" },
  { id: "CAM-P05", name: "Prasad Counter", count: 62, type: "people", status: "NORMAL" },
  { id: "CAM-P06", name: "Parking Lot A", count: 640, type: "vehicles", status: "BUSY" },
  { id: "CAM-P07", name: "North Gate", count: 94, type: "people", status: "NORMAL" },
  { id: "CAM-P08", name: "South Gate", count: 78, type: "people", status: "NORMAL" },
  { id: "CAM-P09", name: "VIP Darshan Lane", count: 34, type: "people", status: "NORMAL" },
  { id: "CAM-P10", name: "Emergency Exit (North)", count: 0, type: "people", status: "CLEAR" },
  { id: "CAM-P11", name: "Temple Office Area", count: 12, type: "people", status: "NORMAL" },
  { id: "CAM-P12", name: "Footwear Counter", count: 89, type: "people", status: "NORMAL" },
];

export const ZONES = [
  { name: "Main Gopuram Entry", capacity: 500, current: 380, status: "BUSY", action: "Open Lane" },
  { name: "Queue Lane A", capacity: 800, current: 620, status: "BUSY", action: "Extend Lane" },
  { name: "Queue Lane B", capacity: 800, current: 540, status: "MODERATE", action: "Monitor" },
  { name: "Inner Sanctum", capacity: 200, current: 145, status: "MODERATE", action: "Monitor" },
  { name: "Prasad Counter", capacity: 150, current: 90, status: "NORMAL", action: "—" },
  { name: "Parking Lot A", capacity: 800, current: 640, status: "BUSY", action: "Overflow Alert" },
  { name: "Parking Lot B", capacity: 500, current: 340, status: "MODERATE", action: "Monitor" },
  { name: "Emergency Exit", capacity: 0, current: 0, status: "CLEAR", action: "—" },
];

export const POOJAS = [
  {
    time: "5:30 AM",
    name: "Ushathkala Pooja (Dawn)",
    status: "done",
    desc: "Early morning worship with Gomotha Pooja to start the day.",
  },
  {
    time: "8:00 AM",
    name: "Kalasandhi Pooja",
    status: "done",
    desc: "Elaborate morning rituals; main vibhuti (sacred ash) is distributed.",
  },
  {
    time: "12:00 PM",
    name: "Uchikala Pooja",
    status: "done",
    desc: "Midday worship with vibrant Vedic chants and offerings.",
  },
  {
    time: "5:30 PM",
    name: "Sayaratchai Pooja (Evening)",
    status: "live",
    desc: "Sunset pooja; a tranquil time for reflection.",
  },
  {
    time: "7:30 PM",
    name: "Irandam Kala Pooja (Second)",
    status: "upcoming",
    desc: "Evening rituals and second-phase night prayers.",
  },
  {
    time: "9:00 PM",
    name: "Arthajama Pooja (Night)",
    status: "upcoming",
    desc: "The final pooja before the temple doors are closed for the night.",
  },
];

export const statusColor = (s: string) => {
  const map: Record<string, string> = {
    NORMAL: "bg-status-normal/15 text-status-normal border-status-normal/30",
    MODERATE: "bg-status-busy/15 text-status-busy border-status-busy/30",
    BUSY: "bg-status-crowded/15 text-status-crowded border-status-crowded/30",
    CROWDED: "bg-status-crowded/15 text-status-crowded border-status-crowded/30",
    CRITICAL: "bg-status-critical/15 text-status-critical border-status-critical/30",
    CLEAR: "bg-status-normal/15 text-status-normal border-status-normal/30",
  };
  return map[s] ?? map.NORMAL;
};

export const densityColor = (pct: number) => {
  if (pct >= 80) return "var(--status-critical)";
  if (pct >= 60) return "var(--status-crowded)";
  if (pct >= 40) return "var(--status-busy)";
  return "var(--status-normal)";
};
