const basePoojas = []; const palaniPoojas = []; const meenakshiPoojas = []; const karnatakaPoojas = []; const maharashtraPoojas = []; const gujaratPoojas = []; module.exports = [
  // Tamil Nadu
  { id:1, slug:"palani-murugan", name:"Palani Murugan Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Palani_Murugan_Temple.jpg?width=800", deityImage: "/deities/murugan_palani_1779692676216.png", deity:"Lord Murugan (Dhandayuthapani Swamy)", state: "Tamil Nadu", district:"Dindigul", city:"Palani", established:"2000+ years", tier:"Tier 1 Major Kshetram", openTime:"06:00", closeTime:"21:00", afternoonClose:"12:30", afternoonOpen:"15:00", crowd:12450, capacity:20000, crowdPct:62, waitMin:45, parking:{lotA:80,lotB:68,overflow:0}, color:"#F97316", gradientFrom:"#FFF7ED", gradientTo:"#FFEDD5", specialDay:"Tuesday", crowdStatus:"MODERATE", poojas: palaniPoojas },
  { id:2, slug:"madurai-meenakshi", name:"Madurai Meenakshi Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/An_aerial_view_of_Madurai_city_from_atop_of_Meenakshi_Amman_temple.jpg?width=800", deityImage: "/deities/meenakshi_madurai_1779692694024.png", deity:"Goddess Meenakshi & Lord Sundareswarar", state: "Tamil Nadu", district:"Madurai", city:"Madurai", openTime:"05:00", closeTime:"22:00", afternoonClose:"12:30", afternoonOpen:"16:00", crowd:18320, capacity:25000, crowdPct:73, waitMin:62, parking:{lotA:91,lotB:78,overflow:45}, color:"#7C3AED", gradientFrom:"#F5F3FF", gradientTo:"#EDE9FE", specialDay:"Friday", crowdStatus:"HIGH", poojas: meenakshiPoojas },
  { id:3, slug:"srirangam", name:"Srirangam Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ranganathaswamy_temple_tiruchirappalli.jpg?width=800", deityImage: "/deities/ranganatha_srirangam_1779692710953.png", deity:"Lord Ranganatha (Vishnu)", state: "Tamil Nadu", district:"Tiruchirappalli", city:"Srirangam", openTime:"06:00", closeTime:"21:00", crowd:9840, capacity:22000, crowdPct:45, waitMin:28, parking:{lotA:54,lotB:38,overflow:0}, color:"#059669", gradientFrom:"#F0FDF4", gradientTo:"#DCFCE7", specialDay:"Saturday", crowdStatus:"LOW", poojas: basePoojas },
  { id:4, slug:"tiruvannamalai", name:"Tiruvannamalai Arunachaleswarar Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Arunachalam_temple_from_a_nearby_hill.jpg?width=800", deityImage: "/deities/shiva_lingam_1779692728170.png", deity:"Lord Shiva (Arunachaleswarar)", state: "Tamil Nadu", district:"Tiruvannamalai", city:"Tiruvannamalai", openTime:"05:30", closeTime:"21:30", crowd:22100, capacity:25000, crowdPct:88, waitMin:85, parking:{lotA:96,lotB:94,overflow:82}, color:"#DC2626", gradientFrom:"#FFF1F2", gradientTo:"#FFE4E6", specialDay:"Full Moon", crowdStatus:"CRITICAL", poojas: basePoojas },
  { id:5, slug:"rameswaram", name:"Rameswaram Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ramanathaswamy_temple7.JPG?width=800", deityImage: "/deities/shiva_lingam_1779692728170.png", deity:"Lord Shiva (Ramanathaswamy)", state: "Tamil Nadu", district:"Ramanathapuram", city:"Rameswaram", openTime:"05:00", closeTime:"21:00", crowd:7650, capacity:20000, crowdPct:38, waitMin:18, parking:{lotA:42,lotB:30,overflow:0}, color:"#0284C7", gradientFrom:"#F0F9FF", gradientTo:"#E0F2FE", specialDay:"Monday", crowdStatus:"LOW", poojas: basePoojas },
  { id:6, slug:"chidambaram", name:"Chidambaram Natarajar Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Le_temple_de_Shiva_Nataraja_(Chidambaram,_Inde)_(14037020332).jpg?width=800", deityImage: "/deities/nataraja_chidambaram_1779692743936.png", deity:"Lord Shiva (Nataraja)", state: "Tamil Nadu", district:"Cuddalore", city:"Chidambaram", openTime:"06:00", closeTime:"22:00", crowd:5320, capacity:18000, crowdPct:30, waitMin:15, parking:{lotA:31,lotB:20,overflow:0}, color:"#B45309", gradientFrom:"#FFFBEB", gradientTo:"#FEF3C7", specialDay:"Friday", crowdStatus:"LOW", poojas: basePoojas },
  { id:7, slug:"tiruchendur", name:"Tiruchendur Murugan Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Thiruchendur_Murugan_Temple.jpg?width=800", deityImage: "/deities/murugan_palani_1779692676216.png", deity:"Lord Murugan (Senthilandavar)", state: "Tamil Nadu", district:"Thoothukudi", city:"Tiruchendur", openTime:"05:00", closeTime:"21:00", crowd:11200, capacity:20000, crowdPct:56, waitMin:35, parking:{lotA:67,lotB:52,overflow:0}, color:"#D97706", gradientFrom:"#FFFBEB", gradientTo:"#FEF9C3", specialDay:"Tuesday", crowdStatus:"MODERATE", poojas: basePoojas },
  { id:8, slug:"samayapuram", name:"Samayapuram Mariamman Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Samayapuram_Mariamman_Temple.jpg?width=800", deityImage: "/deities/mariamman_1779692759158.png", deity:"Goddess Mariamman", state: "Tamil Nadu", district:"Tiruchirappalli", city:"Samayapuram", openTime:"05:30", closeTime:"21:00", crowd:14500, capacity:20000, crowdPct:72, waitMin:52, parking:{lotA:83,lotB:71,overflow:25}, color:"#DB2777", gradientFrom:"#FFF0F9", gradientTo:"#FCE7F3", specialDay:"Sunday", crowdStatus:"HIGH", poojas: basePoojas },
  { id:9, slug:"kapaleeshwarar", name:"Kapaleeshwarar Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kapaleeswarar1.jpg?width=800", deityImage: "/deities/shiva_lingam_1779692728170.png", deity:"Lord Shiva (Kapaleeshwarar)", state: "Tamil Nadu", district:"Chennai", city:"Mylapore, Chennai", openTime:"05:30", closeTime:"22:00", crowd:6400, capacity:15000, crowdPct:43, waitMin:20, parking:{lotA:45,lotB:35,overflow:0}, color:"#0891B2", gradientFrom:"#F0FDFA", gradientTo:"#CCFBF1", specialDay:"Monday", crowdStatus:"LOW", poojas: basePoojas },
  { id:10, slug:"brihadeeswarar", name:"Brihadeeswarar Temple", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Brihadeeswarar_Temple_Thanjavur.jpg?width=800", deityImage: "/deities/shiva_lingam_1779692728170.png", deity:"Lord Shiva (Brihadeeswarar)", state: "Tamil Nadu", district:"Thanjavur", city:"Thanjavur", openTime:"06:00", closeTime:"20:30", crowd:4200, capacity:15000, crowdPct:28, waitMin:12, parking:{lotA:28,lotB:18,overflow:0}, color:"#7C3AED", gradientFrom:"#F5F3FF", gradientTo:"#EDE9FE", specialDay:"Monday", crowdStatus:"LOW", poojas: basePoojas },

  // Karnataka
  { id:11, slug:"virupaksha", name:"Virupaksha Temple", deity:"Lord Shiva", state: "Karnataka", district:"Vijayanagara", city:"Hampi", openTime:"06:00", closeTime:"20:00", crowd:8500, capacity:15000, crowdPct:56, waitMin:30, parking:{lotA:40,lotB:30,overflow:10}, color:"#B45309", gradientFrom:"#FFFBEB", gradientTo:"#FEF3C7", specialDay:"Monday", crowdStatus:"MODERATE", poojas: karnatakaPoojas },
  { id:12, slug:"udupi-sri-krishna", name:"Udupi Sri Krishna Matha", deity:"Lord Krishna", state: "Karnataka", district:"Udupi", city:"Udupi", openTime:"05:30", closeTime:"21:00", crowd:11200, capacity:18000, crowdPct:62, waitMin:40, parking:{lotA:60,lotB:40,overflow:20}, color:"#0284C7", gradientFrom:"#F0F9FF", gradientTo:"#E0F2FE", specialDay:"Wednesday", crowdStatus:"MODERATE", poojas: karnatakaPoojas },
  { id:13, slug:"murudeshwara", name:"Murudeshwara Temple", deity:"Lord Shiva", state: "Karnataka", district:"Uttara Kannada", city:"Murudeshwar", openTime:"06:00", closeTime:"20:30", crowd:15400, capacity:25000, crowdPct:61, waitMin:45, parking:{lotA:100,lotB:80,overflow:30}, color:"#0891B2", gradientFrom:"#F0FDFA", gradientTo:"#CCFBF1", specialDay:"Monday", crowdStatus:"MODERATE", poojas: karnatakaPoojas },
  { id:14, slug:"gokarna-mahabaleshwara", name:"Mahabaleshwara Temple", deity:"Lord Shiva", state: "Karnataka", district:"Uttara Kannada", city:"Gokarna", openTime:"06:00", closeTime:"20:00", crowd:7800, capacity:12000, crowdPct:65, waitMin:50, parking:{lotA:30,lotB:20,overflow:0}, color:"#DC2626", gradientFrom:"#FFF1F2", gradientTo:"#FFE4E6", specialDay:"Monday", crowdStatus:"MODERATE", poojas: karnatakaPoojas },
  { id:15, slug:"chennakeshava", name:"Chennakeshava Temple", deity:"Lord Vishnu", state: "Karnataka", district:"Hassan", city:"Belur", openTime:"07:30", closeTime:"19:30", crowd:4500, capacity:10000, crowdPct:45, waitMin:20, parking:{lotA:50,lotB:20,overflow:0}, color:"#059669", gradientFrom:"#F0FDF4", gradientTo:"#DCFCE7", specialDay:"Saturday", crowdStatus:"LOW", poojas: karnatakaPoojas },
  { id:16, slug:"kukke-subramanya", name:"Kukke Subramanya Temple", deity:"Lord Subramanya", state: "Karnataka", district:"Dakshina Kannada", city:"Subramanya", openTime:"05:00", closeTime:"20:00", crowd:13500, capacity:18000, crowdPct:75, waitMin:70, parking:{lotA:80,lotB:60,overflow:40}, color:"#F97316", gradientFrom:"#FFF7ED", gradientTo:"#FFEDD5", specialDay:"Tuesday", crowdStatus:"HIGH", poojas: karnatakaPoojas },
  { id:17, slug:"dharmasthala", name:"Dharmasthala Temple", deity:"Lord Shiva (Manjunatha)", state: "Karnataka", district:"Dakshina Kannada", city:"Dharmasthala", openTime:"06:30", closeTime:"21:00", crowd:18000, capacity:25000, crowdPct:72, waitMin:60, parking:{lotA:120,lotB:100,overflow:80}, color:"#DC2626", gradientFrom:"#FFF1F2", gradientTo:"#FFE4E6", specialDay:"Monday", crowdStatus:"HIGH", poojas: karnatakaPoojas },
  { id:18, slug:"sringeri", name:"Sringeri Sharada Peetham", deity:"Goddess Sharada", state: "Karnataka", district:"Chikkamagaluru", city:"Sringeri", openTime:"06:00", closeTime:"20:00", crowd:6500, capacity:12000, crowdPct:54, waitMin:25, parking:{lotA:40,lotB:30,overflow:10}, color:"#7C3AED", gradientFrom:"#F5F3FF", gradientTo:"#EDE9FE", specialDay:"Friday", crowdStatus:"MODERATE", poojas: karnatakaPoojas },
  { id:19, slug:"mookambika", name:"Mookambika Temple", deity:"Goddess Mookambika", state: "Karnataka", district:"Udupi", city:"Kollur", openTime:"05:00", closeTime:"21:00", crowd:8200, capacity:15000, crowdPct:54, waitMin:35, parking:{lotA:50,lotB:40,overflow:0}, color:"#DB2777", gradientFrom:"#FFF0F9", gradientTo:"#FCE7F3", specialDay:"Friday", crowdStatus:"MODERATE", poojas: karnatakaPoojas },
  { id:20, slug:"hoysaleswara", name:"Hoysaleswara Temple", deity:"Lord Shiva", state: "Karnataka", district:"Hassan", city:"Halebidu", openTime:"06:30", closeTime:"21:00", crowd:5100, capacity:10000, crowdPct:51, waitMin:20, parking:{lotA:30,lotB:20,overflow:0}, color:"#B45309", gradientFrom:"#FFFBEB", gradientTo:"#FEF3C7", specialDay:"Monday", crowdStatus:"MODERATE", poojas: karnatakaPoojas },

  // Maharashtra
  { id:21, slug:"shirdi-sai", name:"Shirdi Sai Baba Temple", deity:"Sai Baba", state: "Maharashtra", district:"Ahmednagar", city:"Shirdi", openTime:"04:00", closeTime:"22:00", crowd:35000, capacity:40000, crowdPct:87, waitMin:120, parking:{lotA:200,lotB:150,overflow:100}, color:"#F97316", gradientFrom:"#FFF7ED", gradientTo:"#FFEDD5", specialDay:"Thursday", crowdStatus:"CRITICAL", poojas: maharashtraPoojas },
  { id:22, slug:"siddhivinayak", name:"Siddhivinayak Temple", deity:"Lord Ganesha", state: "Maharashtra", district:"Mumbai", city:"Mumbai", openTime:"05:30", closeTime:"21:50", crowd:28000, capacity:30000, crowdPct:93, waitMin:90, parking:{lotA:50,lotB:20,overflow:0}, color:"#DC2626", gradientFrom:"#FFF1F2", gradientTo:"#FFE4E6", specialDay:"Tuesday", crowdStatus:"CRITICAL", poojas: maharashtraPoojas },
  { id:23, slug:"trimbakeshwar", name:"Trimbakeshwar Temple", deity:"Lord Shiva", state: "Maharashtra", district:"Nashik", city:"Trimbak", openTime:"05:30", closeTime:"21:00", crowd:16500, capacity:20000, crowdPct:82, waitMin:75, parking:{lotA:60,lotB:50,overflow:30}, color:"#B45309", gradientFrom:"#FFFBEB", gradientTo:"#FEF3C7", specialDay:"Monday", crowdStatus:"HIGH", poojas: maharashtraPoojas },
  { id:24, slug:"bhimashankar", name:"Bhimashankar Temple", deity:"Lord Shiva", state: "Maharashtra", district:"Pune", city:"Bhimashankar", openTime:"04:30", closeTime:"21:30", crowd:11000, capacity:15000, crowdPct:73, waitMin:50, parking:{lotA:40,lotB:30,overflow:20}, color:"#0891B2", gradientFrom:"#F0FDFA", gradientTo:"#CCFBF1", specialDay:"Monday", crowdStatus:"HIGH", poojas: maharashtraPoojas },
  { id:25, slug:"grishneshwar", name:"Grishneshwar Temple", deity:"Lord Shiva", state: "Maharashtra", district:"Aurangabad", city:"Ellora", openTime:"05:30", closeTime:"21:30", crowd:9500, capacity:15000, crowdPct:63, waitMin:40, parking:{lotA:50,lotB:30,overflow:10}, color:"#059669", gradientFrom:"#F0FDF4", gradientTo:"#DCFCE7", specialDay:"Monday", crowdStatus:"MODERATE", poojas: maharashtraPoojas },
  { id:26, slug:"mahalaxmi-kolhapur", name:"Mahalaxmi Temple", deity:"Goddess Mahalaxmi", state: "Maharashtra", district:"Kolhapur", city:"Kolhapur", openTime:"05:00", closeTime:"22:00", crowd:14000, capacity:20000, crowdPct:70, waitMin:45, parking:{lotA:70,lotB:50,overflow:0}, color:"#DB2777", gradientFrom:"#FFF0F9", gradientTo:"#FCE7F3", specialDay:"Friday", crowdStatus:"HIGH", poojas: maharashtraPoojas },
  { id:27, slug:"shani-shingnapur", name:"Shani Shingnapur", deity:"Lord Shani", state: "Maharashtra", district:"Ahmednagar", city:"Shingnapur", openTime:"00:00", closeTime:"23:59", crowd:12000, capacity:25000, crowdPct:48, waitMin:20, parking:{lotA:100,lotB:50,overflow:20}, color:"#374151", gradientFrom:"#F3F4F6", gradientTo:"#E5E7EB", specialDay:"Saturday", crowdStatus:"LOW", poojas: maharashtraPoojas },
  { id:28, slug:"tulja-bhavani", name:"Tulja Bhavani Temple", deity:"Goddess Bhavani", state: "Maharashtra", district:"Dharashiv", city:"Tuljapur", openTime:"04:00", closeTime:"22:00", crowd:16000, capacity:22000, crowdPct:72, waitMin:55, parking:{lotA:60,lotB:40,overflow:10}, color:"#DC2626", gradientFrom:"#FFF1F2", gradientTo:"#FFE4E6", specialDay:"Tuesday", crowdStatus:"HIGH", poojas: maharashtraPoojas },
  { id:29, slug:"pandharpur-vitthal", name:"Vithoba Temple", deity:"Lord Vitthal", state: "Maharashtra", district:"Solapur", city:"Pandharpur", openTime:"04:00", closeTime:"23:00", crowd:22000, capacity:30000, crowdPct:73, waitMin:80, parking:{lotA:80,lotB:70,overflow:50}, color:"#7C3AED", gradientFrom:"#F5F3FF", gradientTo:"#EDE9FE", specialDay:"Wednesday", crowdStatus:"HIGH", poojas: maharashtraPoojas },
  { id:30, slug:"jejuri-khandoba", name:"Khandoba Temple", deity:"Lord Khandoba", state: "Maharashtra", district:"Pune", city:"Jejuri", openTime:"05:30", closeTime:"21:00", crowd:8500, capacity:15000, crowdPct:56, waitMin:30, parking:{lotA:40,lotB:30,overflow:10}, color:"#D97706", gradientFrom:"#FFFBEB", gradientTo:"#FEF9C3", specialDay:"Sunday", crowdStatus:"MODERATE", poojas: maharashtraPoojas },

  // Gujarat
  { id:31, slug:"somnath", name:"Somnath Temple", deity:"Lord Shiva", state: "Gujarat", district:"Gir Somnath", city:"Prabhas Patan", openTime:"06:00", closeTime:"22:00", crowd:15000, capacity:25000, crowdPct:60, waitMin:45, parking:{lotA:100,lotB:80,overflow:30}, color:"#B45309", gradientFrom:"#FFFBEB", gradientTo:"#FEF3C7", specialDay:"Monday", crowdStatus:"MODERATE", poojas: gujaratPoojas },
  { id:32, slug:"dwarkadhish", name:"Dwarkadhish Temple", deity:"Lord Krishna", state: "Gujarat", district:"Devbhumi Dwarka", city:"Dwarka", openTime:"06:00", closeTime:"21:30", crowd:18000, capacity:25000, crowdPct:72, waitMin:60, parking:{lotA:60,lotB:40,overflow:20}, color:"#0284C7", gradientFrom:"#F0F9FF", gradientTo:"#E0F2FE", specialDay:"Wednesday", crowdStatus:"HIGH", poojas: gujaratPoojas },
  { id:33, slug:"akshardham-gandhinagar", name:"BAPS Akshardham", deity:"Bhagwan Swaminarayan", state: "Gujarat", district:"Gandhinagar", city:"Gandhinagar", openTime:"09:30", closeTime:"19:30", crowd:12000, capacity:30000, crowdPct:40, waitMin:20, parking:{lotA:150,lotB:100,overflow:50}, color:"#F97316", gradientFrom:"#FFF7ED", gradientTo:"#FFEDD5", specialDay:"Sunday", crowdStatus:"LOW", poojas: gujaratPoojas },
  { id:34, slug:"ambaji", name:"Ambaji Temple", deity:"Goddess Amba", state: "Gujarat", district:"Banaskantha", city:"Ambaji", openTime:"07:00", closeTime:"21:00", crowd:14500, capacity:20000, crowdPct:72, waitMin:50, parking:{lotA:80,lotB:60,overflow:20}, color:"#DC2626", gradientFrom:"#FFF1F2", gradientTo:"#FFE4E6", specialDay:"Friday", crowdStatus:"HIGH", poojas: gujaratPoojas },
  { id:35, slug:"modhera-sun", name:"Sun Temple", deity:"Surya (Sun God)", state: "Gujarat", district:"Mehsana", city:"Modhera", openTime:"06:00", closeTime:"18:00", crowd:4000, capacity:10000, crowdPct:40, waitMin:10, parking:{lotA:40,lotB:20,overflow:0}, color:"#D97706", gradientFrom:"#FFFBEB", gradientTo:"#FEF9C3", specialDay:"Sunday", crowdStatus:"LOW", poojas: gujaratPoojas },
  { id:36, slug:"palitana", name:"Palitana Jain Temples", deity:"Adinath", state: "Gujarat", district:"Bhavnagar", city:"Palitana", openTime:"06:00", closeTime:"18:00", crowd:8000, capacity:15000, crowdPct:53, waitMin:30, parking:{lotA:50,lotB:30,overflow:0}, color:"#059669", gradientFrom:"#F0FDF4", gradientTo:"#DCFCE7", specialDay:"Monday", crowdStatus:"MODERATE", poojas: gujaratPoojas },
  { id:37, slug:"rukmini-devi", name:"Rukmini Devi Temple", deity:"Goddess Rukmini", state: "Gujarat", district:"Devbhumi Dwarka", city:"Dwarka", openTime:"06:00", closeTime:"21:00", crowd:5500, capacity:12000, crowdPct:45, waitMin:20, parking:{lotA:20,lotB:10,overflow:0}, color:"#DB2777", gradientFrom:"#FFF0F9", gradientTo:"#FCE7F3", specialDay:"Friday", crowdStatus:"LOW", poojas: gujaratPoojas },
  { id:38, slug:"pavagadh-kalika", name:"Kalika Mata Temple", deity:"Goddess Kalika", state: "Gujarat", district:"Panchmahal", city:"Pavagadh", openTime:"05:00", closeTime:"19:00", crowd:11000, capacity:18000, crowdPct:61, waitMin:45, parking:{lotA:60,lotB:40,overflow:20}, color:"#DC2626", gradientFrom:"#FFF1F2", gradientTo:"#FFE4E6", specialDay:"Tuesday", crowdStatus:"MODERATE", poojas: gujaratPoojas },
  { id:39, slug:"swaminarayan-kalupur", name:"Shree Swaminarayan Mandir", deity:"Nar Narayan", state: "Gujarat", district:"Ahmedabad", city:"Ahmedabad", openTime:"06:00", closeTime:"21:00", crowd:9000, capacity:15000, crowdPct:60, waitMin:25, parking:{lotA:40,lotB:20,overflow:0}, color:"#7C3AED", gradientFrom:"#F5F3FF", gradientTo:"#EDE9FE", specialDay:"Sunday", crowdStatus:"MODERATE", poojas: gujaratPoojas },
  { id:40, slug:"dakor-ranchhodrai", name:"Ranchhodrai Temple", deity:"Lord Krishna", state: "Gujarat", district:"Kheda", city:"Dakor", openTime:"06:00", closeTime:"20:00", crowd:13500, capacity:20000, crowdPct:67, waitMin:40, parking:{lotA:50,lotB:40,overflow:10}, color:"#0284C7", gradientFrom:"#F0F9FF", gradientTo:"#E0F2FE", specialDay:"Full Moon", crowdStatus:"MODERATE", poojas: gujaratPoojas },
]